### ISSUE TITLE
Feature request - Option to choose the ignored directories

### ISSUE THREAD

**Issue by xfr-dev** [imixs/manik-hot-deploy#7]
While looking at the source of the HotdeployBuilder, i saw the multiple directories are ignored for the hot deploy :

``` java
private static String[] IGNORE_DIRECTORIES = { "/src/main/resources/",
"/src/main/java/", "/src/test/resources/", "/src/test/java/",
"/target/m2e-wtp/", "/target/maven-archiver/", "/META-INF/",
"/target/application.xml","/target/test-classes/","/target/classes/","/WEB-INF/classes/" };
```

While I think this is nice to have defaults, it could be nicer to be able to configure/override the ignored directories list.
For example, I would use it to hot deploy "src/main/resources" because, in my case, the resource bundle of the web application reside in this directory.

**Comment by rsoika** [comment]
watch out for the new Maven-based solution 2.0 .....
