### ISSUE TITLE
How to setup Wildfly HOT deployment 

### ISSUE THREAD

**Issue by prefect73** [imixs/manik-hot-deploy#8]
I´m missing a hint, what path to specify for the "Hotdeployment folder" for Wildfly. 
While autodeployment is described in detail, it´s not clear how to get hot deploy running. Could you please add.

**Comment by rsoika** [comment]
If you unpack your build (war files) before deployment, you will find an application folder of your war module in your wildfly deployments folder. 

E.g. [WILDFLY]/deployments/my-app.ear/my-app-web.war/

This is the goal for the hot-deployment. 

If you use maven, make sure that you unpack your build, placed in the target folder.

**Comment by prefect73** [comment]
I have just a web app, no .ear

I did a prepare-package war:exploded in the run configurations and specified the target folder as the hot-deploy directory, but no success.

**Comment by rsoika** [comment]
It doesn't matter if you are working with web or ear. 
Just make sure that the 'hot-deployment path' points to the extracted WAR folder in your wildfly /deployment folder. 
I updated the screenshot:

![screensho](https://raw.githubusercontent.com/rsoika/manik-hot-deploy/master/images/screen06.png)

**Comment by prefect73** [comment]
thanks a lot for your support, but I´m afraid I´m too much of a newbie to the topic.

Do I have to change the maven goal (currently: package wildfly:deploy) or do I have to adjust the pom.xml (currently: <packaging>war</packaging>), or both, in order to make an exploded deploy?

your help is appreciated



Ralph Soika <notifications@github.com> hat am 18. September 2017 um 18:23 geschrieben:


It doesn't matter if you are working with web or ear.
Just make sure that the 'hot-deployment path' points to the extracted WAR folder in your wildfly /deployment folder.
I updated the screenshot:

[screensho] https://raw.githubusercontent.com/rsoika/manik-hot-deploy/master/images/screen06.png

**Comment by itcm3t** [comment]
Is there any way to check logs about this plugin? I am also not able to do hot deploy using above steps
